networks:
  bridge:
    driver: bridge

services:
  db:
    image: postgres:16
    container_name: postgres_data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: analytics
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
      - ./csv/imports:/imports:ro
    networks:
      - bridge

  python:
    build: ./python
    container_name: python_etl
    depends_on:
      - db
    networks:
      - bridge
    ports:
      - "8050:8050"
volumes:
  postgres_data:
